import { connectToDB } from "../utils/database";
import TramStop from "../models/TramStop";
import "dotenv/config";

const tramStops = [
  { name: "Frölunda Torg", location: { lat: 57.652833, lng: 11.911444 } },
  { name: "Opaltorget", location: { lat: 57.642333, lng: 11.901389 } },
  { name: "Östra Sjukhuset", location: { lat: 57.722417, lng: 12.047972 } },
  { name: "Aprilgatan", location: { lat: 57.761111, lng: 12.041528 } },
  { name: "Komettorget", location: { lat: 57.751111, lng: 12.07125 } },
  { name: "Varmfrontsgatan", location: { lat: 57.736889, lng: 11.896611 } },
  { name: "Angered Centrum", location: { lat: 57.795611, lng: 12.049111 } },
  { name: "Vagnhallen Majorna", location: { lat: 57.689111, lng: 11.912194 } },
  { name: "Saltholmen", location: { lat: 57.660611, lng: 11.8455 } },
  { name: "Mölndals Innerstad", location: { lat: 57.656278, lng: 12.017167 } },
  { name: "Brunnsparken", location: { lat: 57.706833, lng: 11.969139 } },
  { name: "Centralstationen", location: { lat: 57.707639, lng: 11.973444 } },
  { name: "Korsvägen", location: { lat: 57.696833, lng: 11.987361 } },
  { name: "Virginsgatan", location: { lat: 57.710861, lng: 12.023528 } }, // converted
  // Remaining stops without coordinates
  { name: "Axel Dahlströms Torg" },
  { name: "Marklandsgatan" },
  { name: "Linnéplatsen" },
  { name: "Olivedalsgatan" },
  { name: "Botaniska Trädgården" },
  { name: "Härlanda" },
  { name: "Stockholmsgatan" },
  { name: "Olskrokstorget" },
  { name: "Redbergsplatsen" },
  { name: "Svingeln" },
  { name: "Ullevi Norra" },
  { name: "Järntorget" },
  { name: "Kaggeledstorget" },
  { name: "Munkebäckstorget" },
  { name: "Tingvallsvägen" },
  { name: "Ättehögsgatan" },
  { name: "Prinsgatan" },
  { name: "Briljantgatan" },
  { name: "Smaragdgatan" },
  { name: "Lantmilsgatan" },
  { name: "Musikvägen" },
  { name: "Nymilsgatan" },
  { name: "Positivgatan" },
  { name: "Stenpiren" },
  { name: "Brunnsgatan" },
  { name: "Seminariegatan" },
  { name: "Mölndals Sjukhus" },
  { name: "Handelshögskolan" },
  { name: "Vasa Viktoriagatan" },
  { name: "Vasaplatsen" },
  { name: "Almedal" },
  { name: "Krokslätts Fabriker" },
  { name: "Krokslätts Torg" },
  { name: "Lackarebäck" },
  { name: "Liseberg Södra" },
  { name: "Elisedal" },
  { name: "Lana" },
  { name: "Varbergsgatan" },
  { name: "Scandinavium" },
  { name: "Ullevi Södra" },
  { name: "Domkyrkan" },
  { name: "Grönsakstorget" },
  { name: "Bokekullsgatan" },
  { name: "Högsbogatan" },
  { name: "Klintens Väg" },
  { name: "Valand" },
  { name: "Kungsportsplatsen" },
  { name: "Sanatoriegatan" },
  { name: "Solrosgatan" },
  { name: "Hagakyrkan" },
  { name: "Chapmans Torg" },
  { name: "Jaegerdorffsplatsen" },
  { name: "Kaptensgatan" },
  { name: "Ostindiegatan" },
  { name: "Masthuggstorget" },
  { name: "Stigbergstorget" },
  { name: "Godhemsgatan" },
  { name: "Mariaplan" },
  { name: "Berzeliigatan" },
  { name: "Gamlestads Torg" },
  { name: "Hammarkullen" },
  { name: "Hjällbo" },
  { name: "Storås" },
  { name: "Bäckeliden" },
  { name: "Bögatan" },
  { name: "Ekmanska" },
  { name: "Lisebergs Station" },
  { name: "Sankt Sigfrids Plan" },
  { name: "Töpelsgatan" },
  { name: "Welandergatan" },
  { name: "Temperaturgatan" },
  { name: "Eketrägatan" },
  { name: "Frihamnen" },
  { name: "Friskväderstorget" },
  { name: "Gropegårdsgatan" },
  { name: "Hjalmar Brantingsplatsen" },
  { name: "Mildvädersgatan" },
  { name: "Rambergsvallen" },
  { name: "Sälöfjordsgatan" },
  { name: "Vågmästareplatsen" },
  { name: "Vårväderstorget" },
  { name: "Väderilsgatan" },
  { name: "Önskevädersgatan" },
  { name: "Wieselgrensplatsen" },
  { name: "Lilla Bommen" },
  { name: "Nordstan" },
  { name: "Medicinaregatan" },
  { name: "Wavrinskys Plats" },
  { name: "Chalmers" },
  { name: "Sahlgrenska Huvudentré" },
  { name: "Allhelgonakyrkan" },
  { name: "Bellevue" },
  { name: "Beväringsgatan" },
  { name: "Kortedala Torg" },
  { name: "Kviberg" },
  { name: "Nymånegatan" },
  { name: "Runstavsgatan" },
  { name: "SKF" },
  { name: "Ejdergatan" },
  { name: "Kapellplatsen" },
  { name: "Galileis Gata" },
  { name: "Januarigatan" },
  { name: "Rymdtorget" },
  { name: "Teleskopgatan" },
  { name: "Sandarna" },
  { name: "Sannaplan" },
  { name: "Kungssten" },
  { name: "Doktor Sydows Gata" },
  { name: "Dr Fries Torg" },
  { name: "Ekedal" },
  { name: "Fjällgatan" },
  { name: "Majvallen" },
  { name: "Roddföreningen" },
  { name: "Hagen" },
  { name: "Hinsholmen" },
  { name: "Käringberget" },
  { name: "Långedrag" },
  { name: "Nya Varvsallén" },
  { name: "Tranered" },
];

async function seed() {
  await connectToDB();
  await TramStop.deleteMany({});
  await TramStop.insertMany(tramStops);
  console.log("✅ Tram stops seeded successfully.");
  process.exit(0);
}

seed();
