import { connectToDB } from "@/utils/database";
import TramStop from "@/models/TramStop";
import TramLine from "@/models/TramLine";
import { NextResponse } from "next/server";

type LineSeedConfig = {
  number: number;
  direction: string;
  reverseDirection: string;
  actualStops: string[];
  segmentMinutes: number[]; // must be actualStops.length - 1
  searchStops: string[];
  reliefStops: string[];
};

const uniquePreserveOrder = (items: string[]) => {
  return [...new Set(items.map((s) => s.trim()))];
};

const sharedReliefStops = [
  "Svingeln",
  "Ullevi Norra",
  "Centralstationen",
  "Vagnhallen Majorna",
  "Jaegerdorffsplatsen",
  "Frihamnen",
  "Hjalmar Brantingsplatsen",
];

const buildReverseConfig = (config: LineSeedConfig): LineSeedConfig => ({
  number: config.number,
  direction: config.reverseDirection,
  reverseDirection: config.direction,
  actualStops: [...config.actualStops].reverse(),
  segmentMinutes: [...config.segmentMinutes].reverse(),
  searchStops: [...config.searchStops].reverse(),
  reliefStops: [...config.reliefStops].reverse(),
});

export async function GET() {
  try {
    await connectToDB();

    const getStopsByNames = async (names: string[]) => {
      const stops = await Promise.all(
        names.map(async (name) => {
          const stop = await TramStop.findOne({ name: name.trim() });
          if (!stop) {
            throw new Error(`Stop not found in TramStop collection: ${name}`);
          }
          return stop;
        }),
      );

      return stops;
    };

    const getStopIds = async (names: string[]) => {
      const stops = await getStopsByNames(names);
      return stops.map((stop) => stop._id);
    };

    const buildTimedRoute = async (
      names: string[],
      segmentMinutes: number[],
    ) => {
      if (names.length !== segmentMinutes.length + 1) {
        throw new Error(
          `Route timing mismatch: ${names.length} stops but ${segmentMinutes.length} segments.`,
        );
      }

      const stops = await getStopsByNames(names);
      let cumulative = 0;

      return stops.map((stop, index) => {
        const entry = {
          stop: stop._id,
          minutesFromStart: cumulative,
        };

        cumulative += segmentMinutes[index] || 0;
        return entry;
      });
    };

    const lineSeeds: LineSeedConfig[] = [
      {
        number: 1,
        direction: "Tynnered",
        reverseDirection: "Östra Sjukhuset",
        actualStops: [
          "Östra Sjukhuset",
          "Tingvallsvägen",
          "Kaggeledstorget",
          "Munkebäckstorget",
          "Härlanda",
          "Stockholmsgatan",
          "Redbergsplatsen",
          "Olskrokstorget",
          "Svingeln",
          "Ullevi Norra",
          "Centralstationen",
          "Brunnsparken",
          "Stenpiren",
          "Järntorget",
          "Prinsgatan",
          "Olivedalsgatan",
          "Linnéplatsen",
          "Botaniska Trädgården",
          "Marklandsgatan",
          "Axel Dahlströms Torg",
          "Lantmilsgatan",
          "Nymilsgatan",
          "Musikvägen",
          "Positivgatan",
          "Frölunda Torg",
          "Briljantgatan",
          "Smaragdgatan",
          "Opaltorget",
        ],
        segmentMinutes: [
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          3, 2, 2, 2, 2, 2, 3, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Östra Sjukhuset",
          "Tingvallsvägen",
          "Kaggeledstorget",
          "Munkebäckstorget",
          "Härlanda",
          "Stockholmsgatan",
          "Redbergsplatsen",
          "Olskrokstorget",
          "Svingeln",
          "Ullevi Norra",
          "Centralstationen",
          "Brunnsparken",
          "Stenpiren",
          "Järntorget",
          "Prinsgatan",
          "Olivedalsgatan",
          "Linnéplatsen",
          "Botaniska Trädgården",
          "Marklandsgatan",
          "Axel Dahlströms Torg",
          "Lantmilsgatan",
          "Nymilsgatan",
          "Musikvägen",
          "Positivgatan",
          "Frölunda Torg",
          "Briljantgatan",
          "Smaragdgatan",
          "Opaltorget",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 2,
        direction: "Biskopsgården",
        reverseDirection: "Högsbotorp",
        actualStops: [
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Linnéplatsen",
          "Olivedalsgatan",
          "Seminariegatan",
          "Brunnsgatan",
          "Handelshögskolan",
          "Vasa Viktoriagatan",
          "Vasaplatsen",
          "Grönsakstorget",
          "Domkyrkan",
          "Brunnsparken",
          "Nordstan",
          "Frihamnen",
          "Hjalmar Brantingsplatsen",
          "Vågmästareplatsen",
          "Wieselgrensplatsen",
          "Rambergsvallen",
          "Gropegårdsgatan",
          "Eketrägatan",
          "Sälöfjordsgatan",
          "Vårväderstorget",
          "Mildvädersgatan",
          "Önskevädersgatan",
          "Friskväderstorget",
          "Väderilsgatan",
        ],
        segmentMinutes: [
          1, 3, 2, 1, 1, 1, 1, 2, 1, 1, 0, 3, 2,
          3, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1,
        ],
        searchStops: uniquePreserveOrder([
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Linnéplatsen",
          "Olivedalsgatan",
          "Seminariegatan",
          "Brunnsgatan",
          "Handelshögskolan",
          "Vasa Viktoriagatan",
          "Vasaplatsen",
          "Grönsakstorget",
          "Domkyrkan",
          "Brunnsparken",
          "Nordstan",
          "Frihamnen",
          "Hjalmar Brantingsplatsen",
          "Vågmästareplatsen",
          "Wieselgrensplatsen",
          "Rambergsvallen",
          "Gropegårdsgatan",
          "Eketrägatan",
          "Sälöfjordsgatan",
          "Vårväderstorget",
          "Mildvädersgatan",
          "Önskevädersgatan",
          "Friskväderstorget",
          "Väderilsgatan",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 3,
        direction: "Kålltorp",
        reverseDirection: "Marklandsgatan",
        actualStops: [
          "Marklandsgatan",
          "Bokekullsgatan",
          "Högsbogatan",
          "Klintens Väg",
          "Godhemsgatan",
          "Mariaplan",
          "Ostindiegatan",
          "Vagnhallen Majorna",
          "Jaegerdorffsplatsen",
          "Chapmans Torg",
          "Kaptensgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Hagakyrkan",
          "Vasa Viktoriagatan",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Centralstationen",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Stockholmsgatan",
          "Härlanda",
          "Solrosgatan",
          "Virginsgatan",
        ],
        segmentMinutes: [
          0, 1, 1, 1, 2, 1, 1, 0, 2, 1, 2, 1, 3, 2,
          2, 1, 1, 1, 2, 1, 3, 2, 1, 2, 1, 1, 1, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Marklandsgatan",
          "Bokekullsgatan",
          "Högsbogatan",
          "Klintens Väg",
          "Godhemsgatan",
          "Mariaplan",
          "Ostindiegatan",
          "Vagnhallen Majorna",
          "Jaegerdorffsplatsen",
          "Chapmans Torg",
          "Kaptensgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Hagakyrkan",
          "Vasa Viktoriagatan",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Centralstationen",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Stockholmsgatan",
          "Härlanda",
          "Solrosgatan",
          "Virginsgatan",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 4,
        direction: "Mölndal",
        reverseDirection: "Angered",
        actualStops: [
          "Angered Centrum",
          "Storås",
          "Hammarkullen",
          "Hjällbo",
          "Gamlestads Torg",
          "Centralstationen",
          "Brunnsparken",
          "Kungsportsplatsen",
          "Valand",
          "Berzeliigatan",
          "Korsvägen",
          "Liseberg Södra",
          "Almedal",
          "Elisedal",
          "Varbergsgatan",
          "Lana",
          "Krokslätts Torg",
          "Krokslätts Fabriker",
          "Lackarebäck",
          "Mölndals Sjukhus",
          "Mölndals Innerstad",
        ],
        segmentMinutes: [
          2, 1, 3, 6, 6, 1, 1, 2, 1, 2,
          1, 2, 1, 1, 1, 0, 1, 2, 1, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Angered Centrum",
          "Storås",
          "Hammarkullen",
          "Hjällbo",
          "Gamlestads Torg",
          "Centralstationen",
          "Brunnsparken",
          "Kungsportsplatsen",
          "Valand",
          "Berzeliigatan",
          "Korsvägen",
          "Liseberg Södra",
          "Almedal",
          "Elisedal",
          "Varbergsgatan",
          "Lana",
          "Krokslätts Torg",
          "Krokslätts Fabriker",
          "Lackarebäck",
          "Mölndals Sjukhus",
          "Mölndals Innerstad",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 6,
        direction: "Kortedala",
        reverseDirection: "Länsmansgården",
        actualStops: [
          "Varmfrontsgatan",
          "Temperaturgatan",
          "Väderilsgatan",
          "Friskväderstorget",
          "Önskevädersgatan",
          "Mildvädersgatan",
          "Vårväderstorget",
          "Sälöfjordsgatan",
          "Eketrägatan",
          "Gropegårdsgatan",
          "Rambergsvallen",
          "Wieselgrensplatsen",
          "Vågmästareplatsen",
          "Hjalmar Brantingsplatsen",
          "Frihamnen",
          "Nordstan",
          "Brunnsparken",
          "Domkyrkan",
          "Grönsakstorget",
          "Hagakyrkan",
          "Järntorget",
          "Prinsgatan",
          "Olivedalsgatan",
          "Linnéplatsen",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Ejdergatan",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Aprilgatan",
        ],
        segmentMinutes: [
          0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 3,
          2, 2, 1, 1, 3, 1, 2, 1, 3, 0, 2, 1, 4, 1, 2,
          2, 2, 1, 2, 1, 3, 0, 2, 2, 1, 1, 1, 1, 1, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Varmfrontsgatan",
          "Temperaturgatan",
          "Väderilsgatan",
          "Friskväderstorget",
          "Önskevädersgatan",
          "Mildvädersgatan",
          "Vårväderstorget",
          "Sälöfjordsgatan",
          "Eketrägatan",
          "Gropegårdsgatan",
          "Rambergsvallen",
          "Wieselgrensplatsen",
          "Vågmästareplatsen",
          "Hjalmar Brantingsplatsen",
          "Frihamnen",
          "Nordstan",
          "Brunnsparken",
          "Domkyrkan",
          "Grönsakstorget",
          "Hagakyrkan",
          "Järntorget",
          "Prinsgatan",
          "Olivedalsgatan",
          "Linnéplatsen",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Ejdergatan",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Aprilgatan",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 7,
        direction: "Bergsjön",
        reverseDirection: "Tynnered",
        actualStops: [
          "Opaltorget",
          "Smaragdgatan",
          "Briljantgatan",
          "Frölunda Torg",
          "Positivgatan",
          "Musikvägen",
          "Nymilsgatan",
          "Lantmilsgatan",
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Kapellplatsen",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Januarigatan",
          "Galileis Gata",
          "Teleskopgatan",
          "Rymdtorget",
          "Komettorget",
        ],
        segmentMinutes: [
          0, 1, 2, 1, 0, 1, 1, 2, 1, 3, 3, 0, 2, 1, 1, 3,
          1, 1, 2, 1, 6, 0, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1,
          1, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Opaltorget",
          "Smaragdgatan",
          "Briljantgatan",
          "Frölunda Torg",
          "Positivgatan",
          "Musikvägen",
          "Nymilsgatan",
          "Lantmilsgatan",
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Kapellplatsen",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Januarigatan",
          "Galileis Gata",
          "Teleskopgatan",
          "Rymdtorget",
          "Komettorget",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 8,
        direction: "Angered",
        reverseDirection: "Frölunda",
        actualStops: [
          "Frölunda Torg",
          "Positivgatan",
          "Musikvägen",
          "Nymilsgatan",
          "Lantmilsgatan",
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Ejdergatan",
          "Gamlestads Torg",
          "Hjällbo",
          "Hammarkullen",
          "Storås",
          "Angered Centrum",
        ],
        segmentMinutes: [
          1, 1, 1, 1, 2, 1, 3, 3, 0, 2, 1, 4,
          1, 2, 2, 2, 1, 2, 1, 3, 6, 2, 2, 3,
        ],
        searchStops: uniquePreserveOrder([
          "Frölunda Torg",
          "Positivgatan",
          "Musikvägen",
          "Nymilsgatan",
          "Lantmilsgatan",
          "Axel Dahlströms Torg",
          "Marklandsgatan",
          "Botaniska Trädgården",
          "Sahlgrenska Huvudentré",
          "Medicinaregatan",
          "Wavrinskys Plats",
          "Chalmers",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Ullevi Norra",
          "Svingeln",
          "Olskrokstorget",
          "Redbergsplatsen",
          "Ejdergatan",
          "Gamlestads Torg",
          "Hjällbo",
          "Hammarkullen",
          "Storås",
          "Angered Centrum",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 9,
        direction: "Angered",
        reverseDirection: "Kungssten",
        actualStops: [
          "Kungssten",
          "Sandarna",
          "Sannaplan",
          "Ostindiegatan",
          "Vagnhallen Majorna",
          "Jaegerdorffsplatsen",
          "Chapmans Torg",
          "Kaptensgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Hagakyrkan",
          "Grönsakstorget",
          "Domkyrkan",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "Hjällbo",
          "Hammarkullen",
          "Storås",
          "Angered Centrum",
        ],
        segmentMinutes: [
          1, 1, 2, 1, 0, 2, 1, 2, 1, 3, 2, 2, 0, 3, 1, 6, 6, 2, 2, 3,
        ],
        searchStops: uniquePreserveOrder([
          "Kungssten",
          "Sandarna",
          "Sannaplan",
          "Ostindiegatan",
          "Vagnhallen Majorna",
          "Jaegerdorffsplatsen",
          "Chapmans Torg",
          "Kaptensgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Hagakyrkan",
          "Grönsakstorget",
          "Domkyrkan",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "Hjällbo",
          "Hammarkullen",
          "Storås",
          "Angered Centrum",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 10,
        direction: "Lindholmen",
        reverseDirection: "Guldheden",
        actualStops: [
          "Doktor Sydows Gata",
          "Doktor Fries Torg",
          "Wavrinskys Plats",
          "Chalmers",
          "Kapellplatsen",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Lilla Bommen",
          "Jubileumsparken",
          "Pumpgatan",
          "Lindholmen",
        ],
        segmentMinutes: [
          0, 2, 1, 1, 3, 1, 1, 2, 0, 4, 4, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Doktor Sydows Gata",
          "Doktor Fries Torg",
          "Wavrinskys Plats",
          "Chalmers",
          "Kapellplatsen",
          "Vasaplatsen",
          "Valand",
          "Kungsportsplatsen",
          "Brunnsparken",
          "Lilla Bommen",
          "Jubileumsparken",
          "Pumpgatan",
          "Lindholmen",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 11,
        direction: "Bergsjön",
        reverseDirection: "Saltholmen",
        actualStops: [
          "Saltholmen",
          "Långedrag",
          "Hinsholmen",
          "Käringberget",
          "Tranered",
          "Hagen",
          "Nya Varvsallén",
          "Kungssten",
          "Sandarna",
          "Sannaplan",
          "Mariaplan",
          "Godhemsgatan",
          "Ekedal",
          "Majvallen",
          "Fjällgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Stenpiren",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Januarigatan",
          "Galileis Gata",
          "Teleskopgatan",
          "Rymdtorget",
          "Komettorget",
        ],
        segmentMinutes: [
          2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 0, 2, 1, 2, 1, 3, 2,
          3, 1, 6, 0, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Saltholmen",
          "Långedrag",
          "Hinsholmen",
          "Käringberget",
          "Tranered",
          "Hagen",
          "Nya Varvsallén",
          "Kungssten",
          "Sandarna",
          "Sannaplan",
          "Mariaplan",
          "Godhemsgatan",
          "Ekedal",
          "Majvallen",
          "Fjällgatan",
          "Stigbergstorget",
          "Masthuggstorget",
          "Järntorget",
          "Stenpiren",
          "Brunnsparken",
          "Centralstationen",
          "Gamlestads Torg",
          "SKF",
          "Bellevue",
          "Kviberg",
          "Beväringsgatan",
          "Nymånegatan",
          "Runstavsgatan",
          "Kortedala Torg",
          "Allhelgonakyrkan",
          "Januarigatan",
          "Galileis Gata",
          "Teleskopgatan",
          "Rymdtorget",
          "Komettorget",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },

      {
        number: 12,
        direction: "Lindholmen",
        reverseDirection: "Mölndal",
        actualStops: [
          "Mölndals Innerstad",
          "Mölndals Sjukhus",
          "Lackarebäck",
          "Krokslätts Fabriker",
          "Krokslätts Torg",
          "Lana",
          "Varbergsgatan",
          "Elisedal",
          "Almedal",
          "Liseberg Södra",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Centralstationen",
          "Nordstan",
          "Jubileumsparken",
          "Pumpgatan",
          "Lindholmen",
        ],
        segmentMinutes: [
          1, 1, 2, 1, 1, 0, 2, 1, 2, 2, 1, 2, 3, 2, 3, 4, 2,
        ],
        searchStops: uniquePreserveOrder([
          "Mölndals Innerstad",
          "Mölndals Sjukhus",
          "Lackarebäck",
          "Krokslätts Fabriker",
          "Krokslätts Torg",
          "Lana",
          "Varbergsgatan",
          "Elisedal",
          "Almedal",
          "Liseberg Södra",
          "Korsvägen",
          "Scandinavium",
          "Ullevi Södra",
          "Centralstationen",
          "Nordstan",
          "Jubileumsparken",
          "Pumpgatan",
          "Lindholmen",
          ...sharedReliefStops,
        ]),
        reliefStops: sharedReliefStops,
      },
    ];

    const fullSeedSet = lineSeeds.flatMap((line) => [
      line,
      buildReverseConfig(line),
    ]);

    const numbers = [...new Set(fullSeedSet.map((l) => l.number))];
    await TramLine.deleteMany({ number: { $in: numbers } });

    const docs = [];

    for (const config of fullSeedSet) {
      const route = await buildTimedRoute(
        config.actualStops,
        config.segmentMinutes,
      );

      const searchRoute = await getStopIds(config.searchStops);
      const reliefPoints = await getStopIds(config.reliefStops);

      docs.push({
        number: config.number,
        direction: config.direction,
        route,
        searchRoute,
        reliefPoints,
      });
    }

    const inserted = await TramLine.insertMany(docs);

    return NextResponse.json({
      message: "✅ Tram lines seeded successfully",
      count: inserted.length,
      seeded: inserted.map((line) => ({
        number: line.number,
        direction: line.direction,
        routeCount: line.route?.length ?? 0,
        searchRouteCount: line.searchRoute?.length ?? 0,
        reliefPointsCount: line.reliefPoints?.length ?? 0,
      })),
    });
  } catch (error: any) {
    console.error("Seeding Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}